### ISSUE TITLE
Implement the frontend

### ISSUE THREAD

**Issue by sandoche** [idea404/near-trust-index#7]
## Tasks
- [ ] Define the UI, confirm with @idea404 
- [ ] Select a frontend framework
- [ ] Write the tests
- [ ] Implement
- [ ] Set up the deployment pipeline (Netlify)

**Comment by AMER88795** [comment]
>  ## Tasks
> - [ ] Define the UI, confirm with @idea404 
> - [ ] Select a frontend framework
> - [ ] Write the tests
> - [ ] Implement
> - [ ] Set up the deployment pipeline (Netlify)

10b77625974f1227f6e01a382fbb29dcbf4131b4
